---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webapp
spec:
  type: {{ .Values.webapp.service.type }}
  ports:
    - port: {{ .Values.webapp.service.port }}
      targetPort: 20000
      nodePort: {{ .Values.webapp.service.nodePort }}
  selector:
    app: webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-webapp
spec:
  replicas: {{ .Values.webapp.replicaCount }}
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
      annotations:
        {{- if .Values.plannings }}
        checksum/config: {{ include (print $.Template.BasePath "/plannings-configmap.yaml") . | sha256sum }}
        {{- end }}
    spec:
      containers:
        - name: webapp
          image: "{{ .Values.webapp.image.repository }}:{{ .Values.webapp.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.webapp.image.pullPolicy }}
          ports:
            - containerPort: 20000
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-webapp-config
          {{- if .Values.plannings }}
          volumeMounts:
            - name: web-plannings-volume
              mountPath: /app/resources/plannings/
          {{- end }}
      {{- if .Values.plannings }}
      volumes:
        - name: web-plannings-volume
          configMap:
            name: {{ .Release.Name }}-web-plannings
      {{- end }}