---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webapp
spec:
  type: {{ .Values.webapp.service.type }}
  ports:
    - port: {{ .Values.webapp.service.port }}
      targetPort: 20000
      nodePort: {{ .Values.webapp.service.nodePort }}
  selector:
    app: webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-webapp
spec:
  replicas: {{ .Values.webapp.replicaCount }}
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
      annotations:
        {{- if .Values.plannings }}
        checksum/config: {{ include (print $.Template.BasePath "/plannings-configmap.yaml") . | sha256sum }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: webapp
          image: "{{ .Values.webapp.image.repository }}:{{ .Values.webapp.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.webapp.image.pullPolicy }}
          ports:
            - containerPort: 20000
          {{- with .Values.webapp.env }}
          env:
          {{- toYaml . | nindent 10 }}
          {{- end }}
          envFrom:
            {{- with .Values.webapp.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - configMapRef:
                name: {{ .Release.Name }}-webapp-config
          {{- if .Values.plannings }}
          volumeMounts:
            - name: web-plannings-volume
              mountPath: /app/plannings
          {{- end }}
          {{- if .Values.webapp.command }}
          command: 
          {{- toYaml .Values.webapp.command | nindent 12 }}
          {{- end }}
          {{- if .Values.webapp.args }}
          args:
          {{- toYaml .Values.webapp.args | nindent 12 }}
          {{- end }}

          resources:
            requests:
              cpu: "10m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "150Mi"
      {{- if .Values.plannings }}
      volumes:
        - name: web-plannings-volume
          configMap:
            name: {{ .Release.Name }}-web-plannings
      {{- end }}